<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Andy" failures="5" tests="13" name="Test" time="14.824" errors="0" timestamp="2021-10-10T15:23:25 IST">
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkContentLength" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.TC001_Get_All_Employee.checkContentLength(TC001_Get_All_Employee.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLength -->
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkContentType" time="0.001"/>
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkContetEncoding" time="0.001"/>
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkResponseBody" time="0.029"/>
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkResponseTime" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.TC001_Get_All_Employee.checkResponseTime(TC001_Get_All_Employee.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseTime -->
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkServerType" time="0.001"/>
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkStatusCode" time="0.002"/>
  <testcase classname="testcases.TC001_Get_All_Employee" name="checkStatusLine" time="0.001"/>
  <testcase classname="testcases.TC002_Post_Request" name="createUser" time="1.87"/>
  <testcase classname="testcases.TC003_Data_Driven" name="createUsers" time="1.333"/>
  <testcase classname="testcases.TC003_Data_Driven" name="createUsers" time="1.312">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;429&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<200> but was:<429>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at org.junit.Assert.assertEquals(Assert.java:456)
at testcases.TC003_Data_Driven.createUsers(TC003_Data_Driven.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createUsers -->
  <testcase classname="testcases.TC003_Data_Driven" name="createUsers" time="1.247">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;429&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<200> but was:<429>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at org.junit.Assert.assertEquals(Assert.java:456)
at testcases.TC003_Data_Driven.createUsers(TC003_Data_Driven.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createUsers -->
  <testcase classname="testcases.TC003_Data_Driven" name="createUsers" time="1.281">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;429&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<200> but was:<429>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at org.junit.Assert.assertEquals(Assert.java:456)
at testcases.TC003_Data_Driven.createUsers(TC003_Data_Driven.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createUsers -->
</testsuite> <!-- Test -->
